rvm: '2.5.0'

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3

script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
